/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import modelo.ModeloTabela;
import controle.ConectaBanco;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rodrigo
 */
public class StaffAtracao extends javax.swing.JFrame {

    ConectaBanco conectaStaff = new ConectaBanco();
    public StaffAtracao() {
        initComponents();
        conectaStaff.conexao();
        conectaStaff.executaSQL("select *from atracao");
        jComboBoxStaffAtracao.removeAllItems();
        try {
            conectaStaff.rs.first();
            do {
                jComboBoxStaffAtracao.addItem(conectaStaff.rs.getString("nome"));
            } while (conectaStaff.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher dropdown eventos" + ex.getMessage());
        }     
      
    }
    
    public void PreencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome", "Funcao", "Setor", "Telefone"}; // aqui são os nomes que irão aparecer nas colunas da tabela
        try {
            conectaStaff.executaSQL(SQL);
            conectaStaff.rs.first();
            do {
                dados.add(new Object[]{conectaStaff.rs.getString("NOME"), conectaStaff.rs.getString("FUNCAO"), conectaStaff.rs.getString("SETOR"), conectaStaff.rs.getString("TELEFONE")});
            } while (conectaStaff.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Prencher o ArrayList!\n ");
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableStaffAtracao.setModel(modelo);
        jTableStaffAtracao.getColumnModel().getColumn(0).setPreferredWidth(125);
        //jTableContrato.getColumnModel().getColumn(0).setResizable(false);
        jTableStaffAtracao.getColumnModel().getColumn(1).setPreferredWidth(125);
        // jTableContrato.getColumnModel().getColumn(1).setResizable(false);
        jTableStaffAtracao.getColumnModel().getColumn(2).setPreferredWidth(125);
        // jTableContrato.getColumnModel().getColumn(2).setResizable(false);
        jTableStaffAtracao.getColumnModel().getColumn(3).setPreferredWidth(125);
        // jTableContrato.getColumnModel().getColumn(3).setResizable(false);
        jTableStaffAtracao.getTableHeader().setReorderingAllowed(false);
        jTableStaffAtracao.setAutoResizeMode(jTableStaffAtracao.AUTO_RESIZE_OFF);
        jTableStaffAtracao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStaffAtracao = new javax.swing.JTable();
        jComboBoxStaffAtracao = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButtonRefreshStaff = new javax.swing.JButton();
        jButtonStaffSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staf das Atrações");

        jTableStaffAtracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableStaffAtracao);

        jComboBoxStaffAtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStaffAtracaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Atração");

        jButtonRefreshStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh.png"))); // NOI18N
        jButtonRefreshStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshStaffActionPerformed(evt);
            }
        });

        jButtonStaffSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sign-out.png"))); // NOI18N
        jButtonStaffSair.setToolTipText("Sair");
        jButtonStaffSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jComboBoxStaffAtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefreshStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonStaffSair, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxStaffAtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRefreshStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonStaffSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStaffAtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStaffAtracaoActionPerformed
      

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStaffAtracaoActionPerformed

    private void jButtonRefreshStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshStaffActionPerformed
        try {
            conectaStaff.conexao();
            conectaStaff.executaSQL("select * from atracao where NOME='"+jComboBoxStaffAtracao.getSelectedItem()+"'");
            conectaStaff.rs.first();
            PreencherTabela("select nome,funcao,setor,telefone from trabalha "
                    + "join staff on staff=pessoa "
                   + "join pessoa on pessoa=cpf "
                   + "where atracao='"+conectaStaff.rs.getString("cnpj")+"'");
        } catch (SQLException ex) {
            Logger.getLogger(StaffAtracao.class.getName()).log(Level.SEVERE, null, ex);
        }
             
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshStaffActionPerformed

    private void jButtonStaffSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonStaffSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffAtracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffAtracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffAtracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffAtracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffAtracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRefreshStaff;
    private javax.swing.JButton jButtonStaffSair;
    private javax.swing.JComboBox jComboBoxStaffAtracao;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStaffAtracao;
    // End of variables declaration//GEN-END:variables
}
